# Generated by Django 4.2.6 on 2023-11-06 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test', max_length=45, unique=True)),
                ('status', models.IntegerField(default=2)),
                ('lat', models.FloatField(default=0.0)),
                ('long', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=45)),
                ('email', models.CharField(default='', max_length=45, unique=True)),
                ('password', models.CharField(default='', max_length=45)),
                ('creation_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('battery_level', models.IntegerField()),
                ('signal_rssi', models.FloatField()),
                ('update_time', models.DateTimeField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sensor')),
            ],
        ),
    ]
