# Generated by Django 4.2.6 on 2023-11-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='sensor',
            name='type',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(default='Sensor-<built-in function id>', max_length=45, unique=True),
        ),
    ]
